language: java
jdk:
  - oraclejdk8
env:
  global:
    CC_TEST_REPORTER_ID=604bfc1f5c5720bb525c572bfa37a3bee177a444e51aae74c92c438b5ebaa01f

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter format-coverage -d -t jacoco ./target/jacoco-ut/jacoco.xml
  - ./cc-test-reporter upload-coverage -d
