language: java
jdk:
  - oraclejdk8

env:
  global:
    - CC_TEST_REPORTER_ID=b6d60b4037822f1a86829a709436583903c3049a9331360d7e5828b43442a3d4
    - JACOCO_SOURCE_PATH=src/main/java

cache:
  directories:
    - $HOME/.m2

before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - mvn clean test

after_script:
  - ./cc-test-reporter format-coverage -d -t jacoco ./target/site/jacoco/jacoco.xml
  - ./cc-test-reporter upload-coverage

